language: node_js

node_js:
  - "5"
  - "6"

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success:
  - test $TRAVIS_BRANCH = "master" && npm run sca $GALAXY_URL $SLACK_WEBHOOK $SLACK_CHANNEL

notifications:
  slack: '$SLACK'